replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54link-dev-notification-service
  pullPolicy: IfNotPresent
  tag: "0.0.4"
nameOverride: ""
fullnameOverride: "notification-service"
serviceAccount:
  create: false
  name: 54agent
podLabels: {}
service:
  type: ClusterIP
  port: 8091
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 200m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
secrets:
  PORT: "8091"
