apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: pos-54link
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.global.environment }}
