replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-verification-ui
  pullPolicy: IfNotPresent
  tag: "0.0.25"
nameOverride: ""
fullnameOverride: "verification-ui"
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: verification-ui
  appPort: 80
  enabled: false
  enableMetrics: false
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  NODE_ENV: "production"
