apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluvio.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "fluvio.name" . }}
    helm.sh/chart: {{ include "fluvio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  fluvio.conf: |
    # Fluvio configuration
    SC_PORT={{ .Values.service.scPort }}
    SPU_PUBLIC_PORT={{ .Values.service.spuPublicPort }}
    SPU_PRIVATE_PORT={{ .Values.service.spuPrivatePort }}
