apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    helm.sh/chart: {{ include "keycloak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  keycloak.conf: |
    db=postgres
    http-enabled=true
    http-port=8080
    proxy=edge
