apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  labels:
    {{- include "tigerbeetle.labels" . | nindent 4 }}
data:
  tigerbeetle.conf: |
    # TigerBeetle configuration
