apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  labels:
    {{- include "tigerbeetle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tb-port
      protocol: TCP
      name: tb-port
  selector:
    {{- include "tigerbeetle.selectorLabels" . | nindent 4 }}
