---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-minio-pdb
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-spark-worker-pdb
  labels:
    app.kubernetes.io/name: spark-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
