apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dapr.fullname" . }}-config
  labels:
    {{- include "dapr.labels" . | nindent 4 }}
data:
  dapr-config.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Configuration
    metadata:
      name: default
    spec:
      tracing:
        samplingRate: "1"
        zipkin:
          endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
