replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-connectivity-sim
  pullPolicy: IfNotPresent
  tag: "0.0.2"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9291
    - port: 9292
    - port: 9293
    - port: 9294
    - port: 9295
    - port: 9296
    - port: 9297
    - port: 9298
    - port: 9299
    - port: 9300
    - port: 9301
    - port: 9302
    - port: 9303
    - port: 9304
    - port: 9305
    - port: 9306
    - port: 9307
    - port: 9308
    - port: 9309
    - port: 9310
resources:
  requests:
    cpu: 200m
    memory: 320Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 1280Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: connectivity-sim
  appPort: 9291
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9291"
  PORT_BASE: "9291"
  SERVICE_GROUP: connectivity-sim
  SERVICES: "airtime-provider-gateway,carrier-billing,carrier-cost-engine,carrier-failover-proxy,carrier-live-api,carrier-performance-reporter,carrier-ranking-engine,carrier-recommendation,carrier-signal-monitor,carrier-sla-monitor,geospatial-service,multi-sim-failover,network-coverage-export,network-diagnostic,network-ml-trainer,network-operations,network-quality-predictor,satellite-connectivity,telco-integration"
