apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: mojaloop
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DB_HOST: {{ .Values.global.mysql.host | quote }}
  DB_PORT: {{ .Values.global.mysql.port | quote }}
  DB_USER: {{ .Values.global.mysql.user | quote }}
  DB_DATABASE: {{ .Values.global.mysql.database | quote }}
  KAFKA_HOST: {{ .Values.global.kafka.host | quote }}
  KAFKA_PORT: {{ .Values.global.kafka.port | quote }}
