replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-core-accounts
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9313
    - port: 9314
    - port: 9315
    - port: 9316
    - port: 9317
    - port: 9318
    - port: 9319
    - port: 9320
    - port: 9321
    - port: 9322
resources:
  requests:
    cpu: 200m
    memory: 160Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 640Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: core-accounts
  appPort: 9313
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9313"
  PORT_BASE: "9313"
  SERVICE_GROUP: core-accounts
  SERVICES: "account-service,beneficiary-service,multi-currency-accounts,multi-currency-engine,multi-currency-wallet,onboarding-service,open-banking,open-banking-api,settings-service,user-onboarding-enhanced"
