# account-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-account-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /account/*
      backends:
        - serviceName: core-accounts
          servicePort: 9313
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/account/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
