# agent-baas
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-agent-baas-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /agent-baas/*
      backends:
        - serviceName: agent-core
          servicePort: 9100
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/agent-baas/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
