# ai-document-validation
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-ai-document-validation-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /ai-document-validation/*
      backends:
        - serviceName: ai-ml
          servicePort: 9149
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ai-document-validation/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
