# aml-case-manager-go
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-aml-case-manager-go-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /aml-case-manager/*
      backends:
        - serviceName: fraud-risk
          servicePort: 9430
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/aml-case-manager/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
