# apisix-gateway
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-apisix-gateway-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /apisix-gateway/*
      backends:
        - serviceName: open-banking-api
          servicePort: 9532
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/apisix-gateway/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
