# at-sms-webhook
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-at-sms-webhook-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /at-sms-webhook/*
      backends:
        - serviceName: channels-social
          servicePort: 9239
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/at-sms-webhook/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
