# at-ussd-handler
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-at-ussd-handler-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /at-ussd-handler/*
      backends:
        - serviceName: channels-ussd-voice
          servicePort: 9275
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/at-ussd-handler/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
