# billing-webhook-dispatcher
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-billing-webhook-dispatcher-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /billing-webhook-dispatcher/*
      backends:
        - serviceName: billing
          servicePort: 9212
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/billing-webhook-dispatcher/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
