# cbn-compliance-comprehensive
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-cbn-compliance-comprehensive-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /cbn-compliance-comprehensive/*
      backends:
        - serviceName: cbn-regulatory
          servicePort: 9226
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/cbn-compliance-comprehensive/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
