# chaos-engineering
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-chaos-engineering-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /chaos-engineering/*
      backends:
        - serviceName: infra-observability
          servicePort: 9481
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/chaos-engineering/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
