# communication-shared
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-communication-shared-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /communication-shared/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9259
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/communication-shared/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
