# developer-portal-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-developer-portal-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /developer-portal/*
      backends:
        - serviceName: open-banking-api
          servicePort: 9533
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/developer-portal/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
    - name: rule-2
      priority: 11
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /developer/*
      backends:
        - serviceName: open-banking-api
          servicePort: 9533
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/developer/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
