# enhanced-platform
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-enhanced-platform-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /enhanced-platform/*
      backends:
        - serviceName: platform-tenant
          servicePort: 9542
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/enhanced-platform/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
