# epr-kgqa-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-epr-kgqa-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /epr-kgqa/*
      backends:
        - serviceName: analytics-data
          servicePort: 9172
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/epr-kgqa/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
