# fee-splitter-realtime
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-fee-splitter-realtime-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /fee-splitter-realtime/*
      backends:
        - serviceName: billing
          servicePort: 9213
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/fee-splitter-realtime/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
