# float-integration-models
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-float-integration-models-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /float-integration-models/*
      backends:
        - serviceName: agent-core
          servicePort: 9120
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/float-integration-models/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
