# iot-smart-pos
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-iot-smart-pos-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /iot-smart-pos/*
      backends:
        - serviceName: agent-pos
          servicePort: 9129
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/iot-smart-pos/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
