# jumia-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-jumia-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /jumia/*
      backends:
        - serviceName: ecommerce-marketplace
          servicePort: 9422
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/jumia/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
