# knowledge-base
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-knowledge-base-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /knowledge-base/*
      backends:
        - serviceName: customer-engagement
          servicePort: 9374
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/knowledge-base/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
