# ledger-integrity-validator
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-ledger-integrity-validator-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /ledger-integrity-validator/*
      backends:
        - serviceName: core-ledger
          servicePort: 9330
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ledger-integrity-validator/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
