# messenger-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-messenger-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /messenger/*
      backends:
        - serviceName: channels-social
          servicePort: 9244
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/messenger/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
