# metaverse-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-metaverse-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /metaverse/*
      backends:
        - serviceName: specialized-finance
          servicePort: 9575
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/metaverse/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
