# monitoring
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-monitoring-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /monitoring/*
      backends:
        - serviceName: infra-observability
          servicePort: 9486
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/monitoring/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
    - name: rule-2
      priority: 11
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /ops/*
      backends:
        - serviceName: infra-observability
          servicePort: 9486
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ops/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
