# multi-sim-failover
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-multi-sim-failover-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /multi-sim-failover/*
      backends:
        - serviceName: connectivity-sim
          servicePort: 9302
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/multi-sim-failover/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
