# multi-currency-accounts
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-multi-currency-accounts-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /multi-currency-accounts/*
      backends:
        - serviceName: core-accounts
          servicePort: 9315
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/multi-currency-accounts/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
