# network-coverage-export
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-network-coverage-export-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /network-coverage-export/*
      backends:
        - serviceName: connectivity-sim
          servicePort: 9303
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/network-coverage-export/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
