# nfc-qr-payments
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-nfc-qr-payments-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /nfc-qr-payments/*
      backends:
        - serviceName: core-payments
          servicePort: 9350
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/nfc-qr-payments/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
