# nigeria-vat-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-nigeria-vat-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /nigeria-vat/*
      backends:
        - serviceName: billing
          servicePort: 9216
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/nigeria-vat/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
    - name: rule-2
      priority: 11
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /vat/*
      backends:
        - serviceName: billing
          servicePort: 9216
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/vat/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
