# payment-processing-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-payment-processing-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /payment-processing/*
      backends:
        - serviceName: core-payments
          servicePort: 9357
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/payment-processing/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
