# pos-hardware-management
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-pos-hardware-management-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /pos-hardware-management/*
      backends:
        - serviceName: agent-pos
          servicePort: 9136
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/pos-hardware-management/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"

    - name: rule-2
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /pos-hardware/*
      backends:
        - serviceName: agent-pos
          servicePort: 9136
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/pos-hardware/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
