# pos-terminal-management
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-pos-terminal-management-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /pos-terminal-management/*
      backends:
        - serviceName: agent-pos
          servicePort: 9141
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/pos-terminal-management/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"

    - name: rule-2
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /pos-terminals/*
      backends:
        - serviceName: agent-pos
          servicePort: 9141
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/pos-terminals/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
