# postgres-production
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-postgres-production-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /postgres-production/*
      backends:
        - serviceName: data-lakehouse
          servicePort: 9395
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/postgres-production/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
