# realtime-notification-service
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-realtime-notification-service-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /realtime-notification/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9265
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/realtime-notification/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"

    - name: rule-2
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /realtime/*
      backends:
        - serviceName: channels-messaging
          servicePort: 9265
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/realtime/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
