# sanctions-etl
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-sanctions-etl-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /sanctions-etl/*
      backends:
        - serviceName: fraud-risk
          servicePort: 9440
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/sanctions-etl/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
