# satellite-connectivity
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-satellite-connectivity-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /satellite-connectivity/*
      backends:
        - serviceName: connectivity-sim
          servicePort: 9308
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/satellite-connectivity/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
