# security-alert
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-security-alert-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /security-alert/*
      backends:
        - serviceName: security
          servicePort: 9564
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/security-alert/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
