# tb-commission-sidecar
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-tb-commission-sidecar-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /tb-commission-sidecar/*
      backends:
        - serviceName: billing
          servicePort: 9220
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/tb-commission-sidecar/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
