# telemetry-api-gateway
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-telemetry-api-gateway-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /telemetry-api-gateway/*
      backends:
        - serviceName: infra-observability
          servicePort: 9488
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/telemetry-api-gateway/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
