# tigerbeetle-integrated
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-tigerbeetle-integrated-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /tigerbeetle-integrated/*
      backends:
        - serviceName: core-ledger
          servicePort: 9334
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/tigerbeetle-integrated/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
