# ussd-localization
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-ussd-localization-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /ussd-localization/*
      backends:
        - serviceName: channels-ussd-voice
          servicePort: 9279
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/ussd-localization/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
