# verification-ui
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-verification-ui-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /verification-ui/*
      backends:
        - serviceName: verification-ui
          servicePort: 80
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/verification-ui/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
