# wearable-payments
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-wearable-payments-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /wearable-payments/*
      backends:
        - serviceName: core-payments
          servicePort: 9367
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/wearable-payments/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
