# webhook-delivery
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-webhook-delivery-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /webhook-delivery/*
      backends:
        - serviceName: realtime-transactions
          servicePort: 9557
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/webhook-delivery/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
