# whatsapp-ai-bot
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-whatsapp-ai-bot-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /whatsapp-ai-bot/*
      backends:
        - serviceName: channels-social
          servicePort: 9251
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/whatsapp-ai-bot/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
