# white-label-api
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-white-label-api-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /white-label-api/*
      backends:
        - serviceName: open-banking-api
          servicePort: 9538
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/white-label-api/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
