# workflow-orchestrator
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: 54agent-workflow-orchestrator-route
  namespace: 54agent
spec:
  ingressClassName: apisix
  http:
    - name: rule-1
      priority: 10
      match:
        hosts:
          - 54agent.upi.dev
        paths:
          - /workflow-orchestrator/*
      backends:
        - serviceName: workflow-orchestration
          servicePort: 9610
      plugins:
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - "^/workflow-orchestrator/(.*)"
              - "/$1"
        - name: cors
          enable: true
          config:
            allow_origins: "*"
            allow_methods: "*"
            allow_headers: "*"
            expose_headers: "*"
