replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-specialized-finance
  pullPolicy: IfNotPresent
  tag: "0.0.5"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9570
    - port: 9571
    - port: 9572
    - port: 9573
    - port: 9574
    - port: 9575
    - port: 9576
    - port: 9577
    - port: 9578
    - port: 9579
    - port: 9580
    - port: 9581
    - port: 9582
resources:
  requests:
    cpu: 200m
    memory: 208Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 832Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: specialized-finance
  appPort: 9573
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9570"
  PORT_BASE: "9570"
  SERVICE_GROUP: specialized-finance
  SERVICES: "blockchain,health-insurance-micro,health-service,insurance-service,investment-service,metaverse-service,pension-micro,stablecoin-defi,stablecoin-integration,stablecoin-rails,stablecoin-v2,tokenized-assets,wealth"
