replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-core-ledger
  pullPolicy: IfNotPresent
  tag: "0.0.3"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9325
    - port: 9326
    - port: 9327
    - port: 9328
    - port: 9329
    - port: 9330
    - port: 9331
    - port: 9332
    - port: 9333
    - port: 9334
    - port: 9335
    - port: 9336
resources:
  requests:
    cpu: 200m
    memory: 160Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 640Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: core-ledger
  appPort: 9325
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  PORT: "9325"
  APP_PORT: "9325"
  PORT_BASE: "9325"
  SERVICE_GROUP: core-ledger
  SERVICES: "chart-of-accounts,core-banking,go-ledger-sync,interest-calculation,ledger-bridge,ledger-integrity-validator,offline-ledger,tigerbeetle-core,tigerbeetle-edge,tigerbeetle-integrated,tigerbeetle-sync,tigerbeetle-zig"
