replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-core-payments
  pullPolicy: IfNotPresent
  tag: "0.0.4"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9339
    - port: 9340
    - port: 9341
    - port: 9342
    - port: 9343
    - port: 9344
    - port: 9345
    - port: 9346
    - port: 9347
    - port: 9348
    - port: 9349
    - port: 9350
    - port: 9351
    - port: 9352
    - port: 9353
    - port: 9354
    - port: 9355
    - port: 9356
    - port: 9357
    - port: 9358
    - port: 9359
    - port: 9360
    - port: 9361
    - port: 9362
    - port: 9363
    - port: 9364
    - port: 9365
    - port: 9366
    - port: 9367
    - port: 9368
resources:
  requests:
    cpu: 200m
    memory: 480Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 1920Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: core-payments
  appPort: 9339
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9339"
  PORT_BASE: "9339"
  SERVICE_GROUP: core-payments
  SERVICES: "bill-payment-gateway,biller-integration,cips-integration,cross-border,currency-conversion,education-payments,fps-integration,global-payment-gateway,instant-reversal-engine,mojaloop-connector,mojaloop-connector-pos,nfc-qr-payments,nfc-tap-to-pay,nibss-integration,papss-integration,payment-corridors-service,payment-gateway-service,payment-hub,payment-processing-service,payment-rails-connectors,payment-split-engine,payout-service,qr-code-service,qr-ticket-verification,sepa-instant,swift-integration,upi-connector,upi-integration,wearable-payments,wise-integration"
