FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /service main.go

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /service /service
EXPOSE 8236
CMD ["/service"]
