import { MapPin, RefreshCw, Search, Zap, ArrowRight, TrendingUp, AlertCircle, CheckCircle } from "lucide-react";
import React, { useEffect, useState } from "react";
import { authHeaders } from "../utils/api";

const CORE_BANKING_URL = import.meta.env.VITE_CORE_BANKING_URL || "https://54agent.upi.dev";

const TYPE_CONFIG = {
  rebalance: { color: "text-blue-400", bg: "bg-blue-900/20", border: "border-blue-700/30", label: "Rebalance", icon: ArrowRight },
  expand:    { color: "text-emerald-400", bg: "bg-emerald-900/20", border: "border-emerald-700/30", label: "Expand", icon: TrendingUp },
  cluster:   { color: "text-purple-400", bg: "bg-purple-900/20", border: "border-purple-700/30", label: "Cluster", icon: Zap },
};

const TerritoryOptimizer = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [applying, setApplying] = useState(null);
  const [applied, setApplied] = useState(new Set());

  useEffect(() => { fetchRecommendations(); }, []);

  const fetchRecommendations = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${CORE_BANKING_URL}/geospatial/api/v1/territories/optimize`, { headers: authHeaders() });
      if (res.ok) {
        const data = await res.json();
        setRecommendations(Array.isArray(data.recommendations) ? data.recommendations : Array.isArray(data) ? data : []);
      } else { setRecommendations([]); }
    } catch { setRecommendations([]); }
    finally { setLoading(false); }
  };

  const applyRecommendation = async (rec) => {
    setApplying(rec.id);
    try {
      await fetch(`${CORE_BANKING_URL}/geospatial/api/v1/territories/optimize/apply`, {
        method: "POST",
        headers: { ...authHeaders(), "Content-Type": "application/json" },
        body: JSON.stringify({ recommendation_id: rec.id }),
      });
      setApplied(prev => new Set([...prev, rec.id]));
    } catch (err) { alert(err.message || "Failed to apply recommendation"); }
    finally { setApplying(null); }
  };

  const filtered = recommendations.filter(r => !searchTerm || JSON.stringify(r).toLowerCase().includes(searchTerm.toLowerCase()));

  return (
    <div className="p-6">
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-purple-600/20 rounded-lg"><Zap className="w-6 h-6 text-purple-400" /></div>
            <div>
              <h1 className="text-2xl font-bold">Territory Optimizer</h1>
              <p className="text-gray-400 text-sm">ML-driven agent territory assignment and network rebalancing</p>
            </div>
          </div>
          <button onClick={fetchRecommendations} className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm hover:bg-gray-700 transition-colors">
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} /> Refresh
          </button>
        </div>

        <div className="bg-blue-900/20 border border-blue-700/30 rounded-lg p-3 flex items-start gap-2 text-xs text-blue-300">
          <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
          <span>Recommendations are generated by ML model using 90-day transaction patterns, population density, and competitor data. Review before applying.</span>
        </div>

        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
          <input value={searchTerm} onChange={e => setSearchTerm(e.target.value)} placeholder="Search recommendations..."
            className="w-full pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500" />
        </div>

        {loading ? (
          <div className="text-center py-12 text-gray-500"><RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2" /> Generating recommendations...</div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-12 text-gray-500 bg-gray-100 border border-gray-200 rounded-xl">
            <MapPin className="w-10 h-10 mx-auto mb-3 opacity-30" />
            <p>No optimization recommendations found</p>
          </div>
        ) : (
          <div className="space-y-4">
            {filtered.map((rec, i) => {
              const cfg = TYPE_CONFIG[rec.type] || TYPE_CONFIG.expand;
              const Icon = cfg.icon;
              const isApplied = applied.has(rec.id);
              return (
                <div key={rec.id || i} className={`border rounded-xl p-5 ${cfg.border} ${cfg.bg}`}>
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex items-start gap-3">
                      <Icon className={`w-5 h-5 mt-0.5 ${cfg.color} shrink-0`} />
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className={`text-xs px-2 py-0.5 rounded-full border ${cfg.border} ${cfg.color} bg-black/20 capitalize`}>{cfg.label}</span>
                          <span className="text-xs text-gray-400">Confidence: <span className={cfg.color}>{rec.confidence}%</span></span>
                        </div>
                        {rec.from && rec.to && (
                          <p className="text-sm font-medium">{rec.from} <ArrowRight className="w-3 h-3 inline mx-1" /> {rec.to}</p>
                        )}
                        {rec.territory && (
                          <p className="text-sm font-medium">{rec.territory}: {rec.recommendation}</p>
                        )}
                        {rec.territories && (
                          <p className="text-sm font-medium">{rec.territories.join(" + ")}: {rec.recommendation}</p>
                        )}
                        <p className="text-xs text-gray-400 mt-1">{rec.reason}</p>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs text-gray-400 mb-1">Impact</p>
                      <p className={`text-sm font-bold ${cfg.color}`}>{rec.impact}</p>
                    </div>
                  </div>
                  <div className="mt-4 flex justify-end">
                    {isApplied ? (
                      <span className="flex items-center gap-1 text-xs text-emerald-400 px-3 py-1.5 bg-emerald-900/30 border border-emerald-700/30 rounded-lg">
                        <CheckCircle className="w-3 h-3" /> Applied
                      </span>
                    ) : (
                      <button onClick={() => applyRecommendation(rec)} disabled={applying === rec.id}
                        className={`flex items-center gap-1 px-4 py-1.5 ${cfg.bg} hover:opacity-80 border ${cfg.border} ${cfg.color} rounded-lg text-xs font-medium transition-opacity disabled:opacity-50`}>
                        {applying === rec.id ? <RefreshCw className="w-3 h-3 animate-spin" /> : <Zap className="w-3 h-3" />}
                        {applying === rec.id ? "Applying..." : "Apply Recommendation"}
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default TerritoryOptimizer;
