"""
Advanced Analytics and Reporting Engine - Production Implementation
Real-time dashboards, custom reports, data export API, predictive analytics

All metrics are computed from a real OLAP store (ClickHouse HTTP interface,
configured via environment). No synthetic/demo datasets are ever generated:
when the store is not configured or unreachable, analytics endpoints return
503 Service Unavailable instead of fabricated metrics.
"""

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict, List, Optional, Any
from datetime import datetime, timedelta
from enum import Enum
import asyncio
import base64
import logging
import json
import os
import urllib.error
import urllib.request

# --- Production: Graceful Shutdown ---
import signal
import sys
import atexit
import logging

_shutdown_handlers = []

def register_shutdown(handler):
    _shutdown_handlers.append(handler)

def _graceful_shutdown(signum, frame):
    sig_name = signal.Signals(signum).name if hasattr(signal, 'Signals') else str(signum)
    logging.info(f"[shutdown] Received {sig_name}, shutting down gracefully...")
    for handler in reversed(_shutdown_handlers):
        try:
            handler()
        except Exception as e:
            logging.warning(f"[shutdown] Handler error: {e}")
    logging.info("[shutdown] Cleanup complete, exiting")
    sys.exit(0)

signal.signal(signal.SIGTERM, _graceful_shutdown)
signal.signal(signal.SIGINT, _graceful_shutdown)
atexit.register(lambda: logging.info("[shutdown] atexit handler called"))


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Advanced Analytics and Reporting", version="1.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])

class ReportType(str, Enum):
    TRANSACTION_SUMMARY = "transaction_summary"
    CORRIDOR_PERFORMANCE = "corridor_performance"
    USER_BEHAVIOR = "user_behavior"
    REVENUE_ANALYSIS = "revenue_analysis"
    GATEWAY_PERFORMANCE = "gateway_performance"
    FRAUD_ANALYTICS = "fraud_analytics"
    COMPLIANCE_REPORT = "compliance_report"

class ExportFormat(str, Enum):
    JSON = "json"
    CSV = "csv"
    PDF = "pdf"
    EXCEL = "excel"

class SubscriptionTier(str, Enum):
    FREE = "free"
    PROFESSIONAL = "professional"
    ENTERPRISE = "enterprise"

class ReportRequest(BaseModel):
    report_type: ReportType
    start_date: str
    end_date: str
    filters: Optional[Dict] = None
    group_by: Optional[List[str]] = None

class DashboardMetrics(BaseModel):
    total_transactions: int
    total_volume: float
    avg_transaction_value: float
    success_rate: float
    top_corridors: List[Dict]
    gateway_distribution: Dict
    hourly_trend: List[Dict]
    timestamp: str

class CustomReport(BaseModel):
    report_id: str
    report_type: ReportType
    data: List[Dict]
    summary: Dict
    generated_at: str
    row_count: int

class OLAPStoreUnavailable(Exception):
    """Raised when the OLAP analytics store is unreachable or not configured."""

class AnalyticsEngine:
    """Advanced Analytics and Reporting Engine.

    Data source: ClickHouse OLAP database over its HTTP interface.
    There is deliberately NO mock/synthetic data path. If CLICKHOUSE_URL is
    unset or the store is unreachable, OLAPStoreUnavailable is raised and the
    API returns 503 - never fabricated metrics.
    """

    def __init__(self):
        self.olap_url = os.environ.get("CLICKHOUSE_URL", "")  # e.g. http://clickhouse:8123
        self.olap_database = os.environ.get("CLICKHOUSE_DATABASE", "analytics")
        self.olap_user = os.environ.get("CLICKHOUSE_USER", "default")
        self.olap_password = os.environ.get("CLICKHOUSE_PASSWORD", "")
        self.transactions_table = os.environ.get("ANALYTICS_TRANSACTIONS_TABLE", "transactions")
        self.olap_timeout = float(os.environ.get("OLAP_QUERY_TIMEOUT_SECONDS", "10"))
        # Registry of reports actually generated by this process. Export only
        # serves reports present here; anything else is a 404.
        self.reports: Dict[str, CustomReport] = {}
        self.subscription_limits = {
            SubscriptionTier.FREE: {"reports_per_month": 5, "export_formats": ["json"], "custom_dashboards": 0},
            SubscriptionTier.PROFESSIONAL: {"reports_per_month": 100, "export_formats": ["json", "csv", "pdf"], "custom_dashboards": 5},
            SubscriptionTier.ENTERPRISE: {"reports_per_month": -1, "export_formats": ["json", "csv", "pdf", "excel"], "custom_dashboards": -1}
        }
        if self.olap_url:
            logger.info("Analytics engine initialized (OLAP store: %s/%s)", self.olap_url, self.olap_database)
        else:
            logger.warning(
                "Analytics engine initialized WITHOUT an OLAP store "
                "(CLICKHOUSE_URL unset); analytics endpoints will return 503"
            )

    # --- OLAP access layer ---
    def _olap_query(self, query: str) -> List[Dict]:
        """Run a read-only query against ClickHouse and return rows as dicts."""
        if not self.olap_url:
            raise OLAPStoreUnavailable("OLAP store is not configured (set CLICKHOUSE_URL)")
        request = urllib.request.Request(
            f"{self.olap_url}/?database={self.olap_database}",
            data=(query + "\nFORMAT JSONEachRow").encode("utf-8"),
        )
        credentials = base64.b64encode(
            f"{self.olap_user}:{self.olap_password}".encode()
        ).decode()
        request.add_header("Authorization", f"Basic {credentials}")
        try:
            with urllib.request.urlopen(request, timeout=self.olap_timeout) as resp:
                body = resp.read().decode("utf-8")
        except (urllib.error.URLError, OSError) as exc:
            raise OLAPStoreUnavailable(f"OLAP store unreachable: {exc}") from exc
        rows = []
        for line in body.splitlines():
            line = line.strip()
            if line:
                rows.append(json.loads(line))
        return rows

    @staticmethod
    def _normalize_timestamp(raw: Any) -> str:
        """Normalize an OLAP timestamp value to ISO-8601 (fromisoformat-safe)."""
        if isinstance(raw, datetime):
            return raw.isoformat()
        return str(raw).replace(" ", "T")

    def _fetch_transactions(self, start: datetime, end: datetime) -> List[Dict]:
        """Fetch real transactions for the given window from the OLAP store."""
        query = (
            "SELECT transaction_id, timestamp, from_country, to_country, "
            "from_currency, to_currency, amount, gateway, status, user_id, fees "
            f"FROM {self.transactions_table} "
            f"WHERE timestamp >= '{start:%Y-%m-%d %H:%M:%S}' "
            f"AND timestamp <= '{end:%Y-%m-%d %H:%M:%S}'"
        )
        rows = self._olap_query(query)
        for row in rows:
            row["timestamp"] = self._normalize_timestamp(row.get("timestamp"))
        return rows

    async def _get_transactions(self, start: datetime, end: datetime) -> List[Dict]:
        """Async wrapper around the blocking OLAP fetch."""
        return await asyncio.to_thread(self._fetch_transactions, start, end)

    async def get_dashboard_metrics(self, start_date: str, end_date: str) -> DashboardMetrics:
        """Get real-time dashboard metrics computed from the OLAP store."""

        start = datetime.fromisoformat(start_date)
        end = datetime.fromisoformat(end_date)

        filtered_txs = await self._get_transactions(start, end)

        # Calculate metrics
        total_transactions = len(filtered_txs)
        completed_txs = [tx for tx in filtered_txs if tx["status"] == "completed"]

        total_volume = sum(tx["amount"] for tx in completed_txs)
        avg_transaction_value = total_volume / len(completed_txs) if completed_txs else 0
        success_rate = len(completed_txs) / total_transactions if total_transactions > 0 else 0

        # Top corridors
        corridor_volumes = {}
        for tx in completed_txs:
            corridor = f"{tx['from_country']}-{tx['to_country']}"
            corridor_volumes[corridor] = corridor_volumes.get(corridor, 0) + tx["amount"]

        top_corridors = [
            {"corridor": k, "volume": round(v, 2), "count": sum(1 for tx in completed_txs if f"{tx['from_country']}-{tx['to_country']}" == k)}
            for k, v in sorted(corridor_volumes.items(), key=lambda x: x[1], reverse=True)[:5]
        ]

        # Gateway distribution
        gateway_counts = {}
        for tx in completed_txs:
            gateway_counts[tx["gateway"]] = gateway_counts.get(tx["gateway"], 0) + 1

        # Hourly trend (last 24 hours)
        hourly_trend = []
        for hour in range(24):
            hour_txs = [tx for tx in completed_txs if datetime.fromisoformat(tx["timestamp"]).hour == hour]
            hourly_trend.append({
                "hour": hour,
                "count": len(hour_txs),
                "volume": round(sum(tx["amount"] for tx in hour_txs), 2)
            })

        logger.info(f"Dashboard metrics: {total_transactions} transactions, ${total_volume:,.2f} volume")

        return DashboardMetrics(
            total_transactions=total_transactions,
            total_volume=round(total_volume, 2),
            avg_transaction_value=round(avg_transaction_value, 2),
            success_rate=round(success_rate, 3),
            top_corridors=top_corridors,
            gateway_distribution=gateway_counts,
            hourly_trend=hourly_trend,
            timestamp=datetime.utcnow().isoformat()
        )

    async def generate_report(self, request: ReportRequest) -> CustomReport:
        """Generate custom report from real OLAP data and register it for export."""

        start = datetime.fromisoformat(request.start_date)
        end = datetime.fromisoformat(request.end_date)

        filtered_txs = await self._get_transactions(start, end)

        # Apply filters
        if request.filters:
            for key, value in request.filters.items():
                filtered_txs = [tx for tx in filtered_txs if tx.get(key) == value]

        # Generate report based on type
        if request.report_type == ReportType.TRANSACTION_SUMMARY:
            data, summary = self._generate_transaction_summary(filtered_txs)
        elif request.report_type == ReportType.CORRIDOR_PERFORMANCE:
            data, summary = self._generate_corridor_performance(filtered_txs)
        elif request.report_type == ReportType.USER_BEHAVIOR:
            data, summary = self._generate_user_behavior(filtered_txs)
        elif request.report_type == ReportType.REVENUE_ANALYSIS:
            data, summary = self._generate_revenue_analysis(filtered_txs)
        elif request.report_type == ReportType.GATEWAY_PERFORMANCE:
            data, summary = self._generate_gateway_performance(filtered_txs)
        else:
            data = filtered_txs[:100]
            summary = {"total_records": len(filtered_txs)}

        report_id = f"RPT-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}-{len(self.reports) + 1}"

        logger.info(f"Generated report {report_id}: {request.report_type}, {len(data)} rows")

        report = CustomReport(
            report_id=report_id,
            report_type=request.report_type,
            data=data,
            summary=summary,
            generated_at=datetime.utcnow().isoformat(),
            row_count=len(data)
        )
        self.reports[report_id] = report
        return report

    def _generate_transaction_summary(self, transactions: List[Dict]) -> tuple:
        """Generate transaction summary report"""
        completed = [tx for tx in transactions if tx["status"] == "completed"]

        data = []
        for tx in completed[:100]:  # Limit to 100 rows
            data.append({
                "date": tx["timestamp"][:10],
                "transaction_id": tx["transaction_id"],
                "corridor": f"{tx['from_country']}-{tx['to_country']}",
                "amount": tx["amount"],
                "currency": tx["from_currency"],
                "gateway": tx["gateway"],
                "fees": tx["fees"],
                "status": tx["status"]
            })

        summary = {
            "total_transactions": len(transactions),
            "completed_transactions": len(completed),
            "failed_transactions": len(transactions) - len(completed),
            "success_rate": round(len(completed) / len(transactions), 3) if transactions else 0,
            "total_volume": round(sum(tx["amount"] for tx in completed), 2),
            "total_fees": round(sum(tx["fees"] for tx in completed), 2)
        }

        return data, summary

    def _generate_corridor_performance(self, transactions: List[Dict]) -> tuple:
        """Generate corridor performance report"""
        corridor_stats = {}

        for tx in transactions:
            corridor = f"{tx['from_country']}-{tx['to_country']}"
            if corridor not in corridor_stats:
                corridor_stats[corridor] = {"count": 0, "volume": 0, "fees": 0, "completed": 0}

            corridor_stats[corridor]["count"] += 1
            if tx["status"] == "completed":
                corridor_stats[corridor]["volume"] += tx["amount"]
                corridor_stats[corridor]["fees"] += tx["fees"]
                corridor_stats[corridor]["completed"] += 1

        data = [
            {
                "corridor": corridor,
                "transaction_count": stats["count"],
                "total_volume": round(stats["volume"], 2),
                "total_fees": round(stats["fees"], 2),
                "success_rate": round(stats["completed"] / stats["count"], 3) if stats["count"] > 0 else 0,
                "avg_transaction_value": round(stats["volume"] / stats["completed"], 2) if stats["completed"] > 0 else 0
            }
            for corridor, stats in corridor_stats.items()
        ]

        summary = {
            "total_corridors": len(corridor_stats),
            "most_active_corridor": max(data, key=lambda x: x["transaction_count"])["corridor"] if data else None,
            "highest_volume_corridor": max(data, key=lambda x: x["total_volume"])["corridor"] if data else None
        }

        return data, summary

    def _generate_user_behavior(self, transactions: List[Dict]) -> tuple:
        """Generate user behavior report"""
        user_stats = {}

        for tx in transactions:
            user_id = tx["user_id"]
            if user_id not in user_stats:
                user_stats[user_id] = {"count": 0, "volume": 0, "last_transaction": None}

            user_stats[user_id]["count"] += 1
            if tx["status"] == "completed":
                user_stats[user_id]["volume"] += tx["amount"]
            user_stats[user_id]["last_transaction"] = tx["timestamp"]

        data = [
            {
                "user_id": user_id,
                "transaction_count": stats["count"],
                "total_volume": round(stats["volume"], 2),
                "avg_transaction_value": round(stats["volume"] / stats["count"], 2) if stats["count"] > 0 else 0,
                "last_transaction": stats["last_transaction"]
            }
            for user_id, stats in list(user_stats.items())[:100]
        ]

        summary = {
            "total_users": len(user_stats),
            "avg_transactions_per_user": round(sum(s["count"] for s in user_stats.values()) / len(user_stats), 2) if user_stats else 0,
            "most_active_user": max(data, key=lambda x: x["transaction_count"])["user_id"] if data else None
        }

        return data, summary

    def _generate_revenue_analysis(self, transactions: List[Dict]) -> tuple:
        """Generate revenue analysis report"""
        completed = [tx for tx in transactions if tx["status"] == "completed"]

        # Group by date
        daily_revenue = {}
        for tx in completed:
            date = tx["timestamp"][:10]
            if date not in daily_revenue:
                daily_revenue[date] = {"fees": 0, "volume": 0, "count": 0}

            daily_revenue[date]["fees"] += tx["fees"]
            daily_revenue[date]["volume"] += tx["amount"]
            daily_revenue[date]["count"] += 1

        data = [
            {
                "date": date,
                "transaction_count": stats["count"],
                "transaction_volume": round(stats["volume"], 2),
                "fee_revenue": round(stats["fees"], 2),
                "avg_fee_per_transaction": round(stats["fees"] / stats["count"], 2) if stats["count"] > 0 else 0
            }
            for date, stats in sorted(daily_revenue.items())
        ]

        summary = {
            "total_revenue": round(sum(tx["fees"] for tx in completed), 2),
            "total_volume": round(sum(tx["amount"] for tx in completed), 2),
            "avg_revenue_per_day": round(sum(d["fee_revenue"] for d in data) / len(data), 2) if data else 0,
            "revenue_margin": round(sum(tx["fees"] for tx in completed) / sum(tx["amount"] for tx in completed) * 100, 2) if completed else 0
        }

        return data, summary

    def _generate_gateway_performance(self, transactions: List[Dict]) -> tuple:
        """Generate gateway performance report"""
        gateway_stats = {}

        for tx in transactions:
            gateway = tx["gateway"]
            if gateway not in gateway_stats:
                gateway_stats[gateway] = {"count": 0, "completed": 0, "failed": 0, "volume": 0}

            gateway_stats[gateway]["count"] += 1
            if tx["status"] == "completed":
                gateway_stats[gateway]["completed"] += 1
                gateway_stats[gateway]["volume"] += tx["amount"]
            else:
                gateway_stats[gateway]["failed"] += 1

        data = [
            {
                "gateway": gateway,
                "total_transactions": stats["count"],
                "completed": stats["completed"],
                "failed": stats["failed"],
                "success_rate": round(stats["completed"] / stats["count"], 3) if stats["count"] > 0 else 0,
                "total_volume": round(stats["volume"], 2)
            }
            for gateway, stats in gateway_stats.items()
        ]

        summary = {
            "total_gateways": len(gateway_stats),
            "best_performing_gateway": max(data, key=lambda x: x["success_rate"])["gateway"] if data else None,
            "highest_volume_gateway": max(data, key=lambda x: x["total_volume"])["gateway"] if data else None
        }

        return data, summary

    async def export_report(self, report: CustomReport, format: ExportFormat) -> Dict:
        """Export report in specified format."""

        if format == ExportFormat.JSON:
            return {"format": "json", "data": report.dict()}

        elif format == ExportFormat.CSV:
            csv_content = self._generate_csv(report.data)
            return {"format": "csv", "content": csv_content, "filename": f"{report.report_id}.csv"}

        elif format == ExportFormat.PDF:
            # No PDF renderer backend is wired up; fail loudly instead of
            # pretending a PDF was produced.
            raise HTTPException(status_code=501, detail="PDF export is not implemented: no PDF renderer backend configured")

        elif format == ExportFormat.EXCEL:
            raise HTTPException(status_code=501, detail="Excel export is not implemented: no Excel renderer backend configured")

    def _generate_csv(self, data: List[Dict]) -> str:
        """Generate CSV content from data"""
        if not data:
            return ""

        headers = list(data[0].keys())
        csv_lines = [",".join(headers)]

        for row in data:
            csv_lines.append(",".join(str(row.get(h, "")) for h in headers))

        return "\n".join(csv_lines)

# Initialize engine
analytics_engine = AnalyticsEngine()

@app.get("/health")
async def health_check():
    configured = bool(analytics_engine.olap_url)
    return {
        "status": "healthy" if configured else "degraded",
        "service": "advanced-analytics",
        "olap_store": "configured" if configured else "not configured (CLICKHOUSE_URL unset)"
    }

@app.get("/api/v1/analytics/dashboard", response_model=DashboardMetrics)
async def get_dashboard(
    start_date: str = Query(..., description="Start date (ISO format)"),
    end_date: str = Query(..., description="End date (ISO format)")
):
    """Get real-time dashboard metrics"""
    try:
        result = await analytics_engine.get_dashboard_metrics(start_date, end_date)
        return result
    except OLAPStoreUnavailable as e:
        logger.error(f"OLAP store unavailable: {e}")
        raise HTTPException(status_code=503, detail=f"Analytics store unavailable: {e}")
    except Exception as e:
        logger.error(f"Dashboard error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Dashboard generation failed: {str(e)}")

@app.post("/api/v1/analytics/reports/generate", response_model=CustomReport)
async def generate_report(request: ReportRequest):
    """Generate custom report"""
    try:
        result = await analytics_engine.generate_report(request)
        return result
    except OLAPStoreUnavailable as e:
        logger.error(f"OLAP store unavailable: {e}")
        raise HTTPException(status_code=503, detail=f"Analytics store unavailable: {e}")
    except Exception as e:
        logger.error(f"Report generation error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")

@app.post("/api/v1/analytics/reports/export")
async def export_report(report_id: str, format: ExportFormat):
    """Export a previously generated report in the specified format.

    Only reports that were actually generated by this service can be exported;
    unknown report IDs are a 404 (no synthetic sample reports).
    """
    report = analytics_engine.reports.get(report_id)
    if report is None:
        raise HTTPException(
            status_code=404,
            detail=f"Report '{report_id}' not found; generate it first via /api/v1/analytics/reports/generate"
        )
    try:
        result = await analytics_engine.export_report(report, format)
        return result
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Export error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Export failed: {str(e)}")

@app.get("/api/v1/analytics/subscription/limits")
async def get_subscription_limits(tier: SubscriptionTier):
    """Get subscription tier limits"""
    return analytics_engine.subscription_limits[tier]

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8035)
