replicaCount: 4

image:
  repository: ghcr.io/permify/permify
  pullPolicy: IfNotPresent
  tag: "v1.2.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  grpcPort: 3476
  httpPort: 3478

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: "4"
    memory: 8Gi
  requests:
    cpu: "2"
    memory: 4Gi

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - permify
        topologyKey: kubernetes.io/hostname

config:
  PERMIFY_DATABASE_ENGINE: "postgres"
  PERMIFY_DATABASE_URI: "postgres://permify:$PERMIFY_DB_PASSWORD@pgbouncer:6432/permify?sslmode=disable"
  PERMIFY_DATABASE_MAX_OPEN_CONNECTIONS: "200"
  PERMIFY_DATABASE_MAX_IDLE_CONNECTIONS: "50"
  PERMIFY_DATABASE_MAX_CONNECTION_LIFETIME: "1800s"
  PERMIFY_SERVICE_CIRCUIT_BREAKER: "true"
  PERMIFY_LOG_LEVEL: "warn"
  PERMIFY_AUTHN_ENABLED: "true"
  PERMIFY_AUTHN_METHOD: "preshared"
  PERMIFY_HTTP_PORT: "3478"
  PERMIFY_GRPC_PORT: "3476"
  PERMIFY_PROFILER_ENABLED: "true"
  PERMIFY_PROFILER_PORT: "6060"

initContainers:
  enabled: true
  image:
    repository: ghcr.io/permify/permify
    tag: "v1.2.2"
  command: ["permify", "migrate"]
