apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    helm.sh/chart: {{ include "postgresql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
    {{- if .Values.pgbouncer.enabled }}
    - port: {{ .Values.pgbouncer.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "postgresql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
