//
// SecurityView.swift
// RemittanceApp
//
// Generated by Manus AI
//

import SwiftUI
import Combine
import LocalAuthentication

// MARK: - Security API (real backend client)

/// Security settings as returned by the backend.
struct SecuritySettings: Codable {
    var isTwoFactorEnabled: Bool
    var isBiometricEnabled: Bool
    var isPinSet: Bool
    var trustedDevices: [Device]
}

/// A trusted device registered on the account.
struct Device: Identifiable, Codable {
    let id: String
    let name: String
    let lastUsed: Date
    let isCurrent: Bool
}

enum SecurityAPIError: Error, LocalizedError {
    case networkError
    case invalidResponse
    case serverError(String)

    var errorDescription: String? {
        switch self {
        case .networkError: return "Could not connect to the network."
        case .invalidResponse: return "Received an invalid response from the server."
        case .serverError(let message): return message
        }
    }
}

/// Interface for the security settings backend, allowing DEBUG-only mocks.
protocol SecurityAPI {
    func fetchSecuritySettings() -> AnyPublisher<SecuritySettings, SecurityAPIError>
    func updateSetting(key: String, value: Bool) -> AnyPublisher<Void, SecurityAPIError>
    func logoutDevice(id: String) -> AnyPublisher<Void, SecurityAPIError>
    func setPin(pin: String) -> AnyPublisher<Void, SecurityAPIError>
}

/// Real security client backed by the 54agent backend security endpoints.
/// Security state (2FA, PIN, trusted devices) is only ever what the server
/// reports — never a fabricated default.
class LiveSecurityAPIClient: SecurityAPI {
    private struct EmptyResponse: Decodable {}

    func fetchSecuritySettings() -> AnyPublisher<SecuritySettings, SecurityAPIError> {
        Future { promise in
            Task {
                do {
                    let settings: SecuritySettings = try await APIClient.shared.request(.securitySettings)
                    promise(.success(settings))
                } catch {
                    promise(.failure(.serverError(error.localizedDescription)))
                }
            }
        }
        .eraseToAnyPublisher()
    }

    func updateSetting(key: String, value: Bool) -> AnyPublisher<Void, SecurityAPIError> {
        Future { promise in
            Task {
                do {
                    let _: EmptyResponse = try await APIClient.shared.request(
                        .securitySetting(key),
                        method: .put,
                        parameters: ["value": value]
                    )
                    promise(.success(()))
                } catch {
                    promise(.failure(.serverError(error.localizedDescription)))
                }
            }
        }
        .eraseToAnyPublisher()
    }

    func logoutDevice(id: String) -> AnyPublisher<Void, SecurityAPIError> {
        Future { promise in
            Task {
                do {
                    let _: EmptyResponse = try await APIClient.shared.request(
                        .securityDeviceLogout(id),
                        method: .post
                    )
                    promise(.success(()))
                } catch {
                    promise(.failure(.serverError(error.localizedDescription)))
                }
            }
        }
        .eraseToAnyPublisher()
    }

    func setPin(pin: String) -> AnyPublisher<Void, SecurityAPIError> {
        guard pin.count == 4, pin.allSatisfy({ $0.isNumber }) else {
            return Fail(error: SecurityAPIError.serverError("PIN must be 4 digits.")).eraseToAnyPublisher()
        }
        return Future { promise in
            Task {
                do {
                    let _: EmptyResponse = try await APIClient.shared.request(
                        .securityPin,
                        method: .post,
                        parameters: ["pin": pin]
                    )
                    promise(.success(()))
                } catch {
                    promise(.failure(.serverError(error.localizedDescription)))
                }
            }
        }
        .eraseToAnyPublisher()
    }
}

#if DEBUG
/// Mock security client (DEBUG builds only, for previews/tests).
class MockSecurityAPIClient: SecurityAPI {
    func fetchSecuritySettings() -> AnyPublisher<SecuritySettings, SecurityAPIError> {
        Future { promise in
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
                let settings = SecuritySettings(
                    isTwoFactorEnabled: true,
                    isBiometricEnabled: false,
                    isPinSet: true,
                    trustedDevices: [
                        Device(id: "1", name: "iPhone 15 Pro (Current)", lastUsed: Date(), isCurrent: true)
                    ]
                )
                promise(.success(settings))
            }
        }
        .eraseToAnyPublisher()
    }

    func updateSetting(key: String, value: Bool) -> AnyPublisher<Void, SecurityAPIError> {
        Just(()).setFailureType(to: SecurityAPIError.self).eraseToAnyPublisher()
    }

    func logoutDevice(id: String) -> AnyPublisher<Void, SecurityAPIError> {
        Just(()).setFailureType(to: SecurityAPIError.self).eraseToAnyPublisher()
    }

    func setPin(pin: String) -> AnyPublisher<Void, SecurityAPIError> {
        Just(()).setFailureType(to: SecurityAPIError.self).eraseToAnyPublisher()
    }
}
#endif

// MARK: - ViewModel

/// Manages the state and business logic for the SecurityView.
final class SecurityViewModel: ObservableObject {
    @Published var settings: SecuritySettings?
    @Published var isLoading: Bool = false
    @Published var errorMessage: String?
    @Published var showPinSetup: Bool = false
    @Published var newPin: String = ""
    @Published var confirmPin: String = ""
    @Published var pinValidationMessage: String?
    
    private var apiClient: SecurityAPI
    private var cancellables = Set<AnyCancellable>()
    private let context = LAContext()

    init(apiClient: SecurityAPI = LiveSecurityAPIClient()) {
        self.apiClient = apiClient
        fetchSettings()
    }
    
    // MARK: - Data Fetching and Caching
    
    /// Fetches security settings from the API.
    func fetchSettings() {
        isLoading = true
        errorMessage = nil
        
        apiClient.fetchSecuritySettings()
            .receive(on: DispatchQueue.main)
            .sink { [weak self] completion in
                self?.isLoading = false
                if case .failure(let error) = completion {
                    self?.errorMessage = error.localizedDescription
                }
            } receiveValue: { [weak self] settings in
                self?.settings = settings
                self?.cacheSettings(settings)
            }
            .store(in: &cancellables)
    }
    
    /// Caches the security settings for offline mode.
    private func cacheSettings(_ settings: SecuritySettings) {
        if let encoded = try? JSONEncoder().encode(settings) {
            UserDefaults.standard.set(encoded, forKey: "cachedSecuritySettings")
        }
    }
    
    // MARK: - Security Feature Toggles
    
    /// Toggles a security setting and handles API communication.
    func toggleSetting(keyPath: WritableKeyPath<SecuritySettings, Bool>, newValue: Bool) {
        guard var currentSettings = settings else { return }
        
        // Optimistic UI update
        let oldValue = currentSettings[keyPath: keyPath]
        currentSettings[keyPath: keyPath] = newValue
        settings = currentSettings
        
        // Special handling for Biometric
        if keyPath == \SecuritySettings.isBiometricEnabled {
            if newValue {
                authenticateBiometrics { [weak self] success in
                    if !success {
                        // Revert on failure
                        self?.settings?[keyPath: keyPath] = oldValue
                        self?.errorMessage = "Biometric authentication failed or was cancelled."
                    } else {
                        self?.updateSettingOnServer(key: "isBiometricEnabled", value: newValue, keyPath: keyPath, oldValue: oldValue)
                    }
                }
            } else {
                updateSettingOnServer(key: "isBiometricEnabled", value: newValue, keyPath: keyPath, oldValue: oldValue)
            }
        } else {
            // General setting update
            let key = keyPath == \SecuritySettings.isTwoFactorEnabled ? "isTwoFactorEnabled" : "unknown"
            updateSettingOnServer(key: key, value: newValue, keyPath: keyPath, oldValue: oldValue)
        }
    }
    
    private func updateSettingOnServer(key: String, value: Bool, keyPath: WritableKeyPath<SecuritySettings, Bool>, oldValue: Bool) {
        apiClient.updateSetting(key: key, value: value)
            .receive(on: DispatchQueue.main)
            .sink { [weak self] completion in
                if case .failure(let error) = completion {
                    // Revert UI on API failure
                    self?.settings?[keyPath: keyPath] = oldValue
                    self?.errorMessage = "Failed to update setting: \(error.localizedDescription)"
                }
            } receiveValue: { _ in
                // Success, nothing to do as UI was updated optimistically
            }
            .store(in: &cancellables)
    }
    
    // MARK: - Biometric Authentication
    
    /// Checks if biometric authentication is available.
    var isBiometricAvailable: Bool {
        var error: NSError?
        return context.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &error)
    }
    
    /// Returns the type of biometric authentication available.
    var biometricType: String {
        if isBiometricAvailable {
            if context.biometryType == .faceID {
                return "Face ID"
            } else if context.biometryType == .touchID {
                return "Touch ID"
            }
        }
        return "Biometric"
    }
    
    /// Performs biometric authentication.
    func authenticateBiometrics(completion: @escaping (Bool) -> Void) {
        guard isBiometricAvailable else {
            completion(false)
            return
        }
        
        let reason = "Enable \(biometricType) for quick and secure access."
        context.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: reason) { success, error in
            DispatchQueue.main.async {
                completion(success)
            }
        }
    }
    
    // MARK: - PIN Management
    
    /// Validates the PIN input.
    var isPinValid: Bool {
        newPin.count == 4 && newPin == confirmPin
    }
    
    /// Submits the new PIN to the API.
    func submitPin() {
        guard isPinValid else {
            pinValidationMessage = "PINs must match and be 4 digits."
            return
        }
        
        isLoading = true
        pinValidationMessage = nil
        
        apiClient.setPin(pin: newPin)
            .receive(on: DispatchQueue.main)
            .sink { [weak self] completion in
                self?.isLoading = false
                if case .failure(let error) = completion {
                    self?.pinValidationMessage = error.localizedDescription
                } else {
                    self?.settings?.isPinSet = true
                    self?.showPinSetup = false
                    self?.newPin = ""
                    self?.confirmPin = ""
                }
            } receiveValue: { _ in }
            .store(in: &cancellables)
    }
    
    // MARK: - Device Management
    
    /// Logs out a specific device.
    func logoutDevice(_ device: Device) {
        guard var currentSettings = settings else { return }
        
        apiClient.logoutDevice(id: device.id)
            .receive(on: DispatchQueue.main)
            .sink { [weak self] completion in
                if case .failure(let error) = completion {
                    self?.errorMessage = "Failed to log out device: \(error.localizedDescription)"
                }
            } receiveValue: { [weak self] _ in
                // Remove device from the list on success
                currentSettings.trustedDevices.removeAll { $0.id == device.id }
                self?.settings = currentSettings
            }
            .store(in: &cancellables)
    }
    
    // MARK: - Payment Gateway Integration Placeholder
    
    /// Placeholder for initiating a payment gateway security check/setup.
    func initiatePaymentGatewaySecuritySetup(gateway: String) {
        // In a real app, this would navigate to a specific flow for Paystack/Flutterwave/Interswitch
        // to set up transaction PINs, security questions, or 2FA for payments.
        print("Initiating security setup for \(gateway)...")
        errorMessage = "Security setup flow for \(gateway) initiated (Placeholder)."
    }
}

// MARK: - View

struct SecurityView: View {
    @StateObject var viewModel = SecurityViewModel()
    
    var body: some View {
        NavigationView {
            Group {
                if viewModel.isLoading && viewModel.settings == nil {
                    ProgressView("Loading Security Settings...")
                } else if let settings = viewModel.settings {
                    List {
                        securityFeaturesSection(settings: settings)
                        pinManagementSection(settings: settings)
                        biometricSection(settings: settings)
                        deviceManagementSection(settings: settings)
                        paymentGatewaySection()
                    }
                    .listStyle(.insetGrouped)
                } else {
                    errorView
                }
            }
            .navigationTitle("Security")
            .refreshable {
                viewModel.fetchSettings()
            }
            .alert("Error", isPresented: .constant(viewModel.errorMessage != nil), actions: {
                Button("OK") { viewModel.errorMessage = nil }
            }, message: {
                Text(viewModel.errorMessage ?? "An unknown error occurred.")
            })
            .sheet(isPresented: $viewModel.showPinSetup) {
                pinSetupSheet
            }
        }
    }
    
    // MARK: - View Components
    
    private var errorView: some View {
        VStack {
            Text("Failed to load settings.")
                .foregroundColor(.secondary)
            Button("Retry") {
                viewModel.fetchSettings()
            }
            .padding()
        }
    }
    
    @ViewBuilder
    private func securityFeaturesSection(settings: SecuritySettings) -> some View {
        Section("Account Security") {
            Toggle("Two-Factor Authentication (2FA)", isOn: Binding(
                get: { settings.isTwoFactorEnabled },
                set: { viewModel.toggleSetting(keyPath: \.isTwoFactorEnabled, newValue: $0) }
            ))
            .accessibilityLabel("Two-Factor Authentication")
            
            NavigationLink {
                // Placeholder for a dedicated 2FA setup/management view
                Text("2FA Management View")
            } label: {
                HStack {
                    Text("Manage 2FA Methods")
                    Spacer()
                    Text(settings.isTwoFactorEnabled ? "Active" : "Inactive")
                        .foregroundColor(.secondary)
                }
            }
        }
    }
    
    @ViewBuilder
    private func pinManagementSection(settings: SecuritySettings) -> some View {
        Section("Transaction PIN") {
            Button(settings.isPinSet ? "Change Transaction PIN" : "Set Transaction PIN") {
                viewModel.showPinSetup = true
            }
            .accessibilityLabel(settings.isPinSet ? "Change Transaction PIN" : "Set Transaction PIN")
        }
    }
    
    @ViewBuilder
    private func biometricSection(settings: SecuritySettings) -> some View {
        if viewModel.isBiometricAvailable {
            Section("Biometric Security") {
                Toggle("Enable \(viewModel.biometricType)", isOn: Binding(
                    get: { settings.isBiometricEnabled },
                    set: { viewModel.toggleSetting(keyPath: \.isBiometricEnabled, newValue: $0) }
                ))
                .accessibilityLabel("Enable \(viewModel.biometricType)")
            }
        }
    }
    
    @ViewBuilder
    private func deviceManagementSection(settings: SecuritySettings) -> some View {
        Section("Trusted Devices") {
            ForEach(settings.trustedDevices) { device in
                HStack {
                    VStack(alignment: .leading) {
                        Text(device.name)
                            .fontWeight(device.isCurrent ? .bold : .regular)
                        Text("Last used: \(device.lastUsed, style: .date)")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    Spacer()
                    if !device.isCurrent {
                        Button("Logout") {
                            viewModel.logoutDevice(device)
                        }
                        .foregroundColor(.red)
                        .accessibilityLabel("Logout \(device.name)")
                    } else {
                        Text("Current Device")
                            .font(.caption)
                            .foregroundColor(.green)
                    }
                }
            }
        }
    }
    
    @ViewBuilder
    private func paymentGatewaySection() -> some View {
        Section("Payment Security") {
            Text("Integrate with payment gateways (Paystack, Flutterwave, Interswitch) for transaction security.")
                .font(.caption)
                .foregroundColor(.secondary)
            
            Button("Setup Paystack Security") {
                viewModel.initiatePaymentGatewaySecuritySetup(gateway: "Paystack")
            }
            Button("Setup Flutterwave Security") {
                viewModel.initiatePaymentGatewaySecuritySetup(gateway: "Flutterwave")
            }
            Button("Setup Interswitch Security") {
                viewModel.initiatePaymentGatewaySecuritySetup(gateway: "Interswitch")
            }
        }
    }
    
    private var pinSetupSheet: some View {
        NavigationView {
            Form {
                Section("Set New Transaction PIN") {
                    SecureField("New 4-Digit PIN", text: $viewModel.newPin)
                        .keyboardType(.numberPad)
                        .accessibilityLabel("New 4-Digit PIN")
                    
                    SecureField("Confirm PIN", text: $viewModel.confirmPin)
                        .keyboardType(.numberPad)
                        .accessibilityLabel("Confirm 4-Digit PIN")
                    
                    if let message = viewModel.pinValidationMessage {
                        Text(message)
                            .foregroundColor(.red)
                    }
                }
                
                Section {
                    Button("Save PIN") {
                        viewModel.submitPin()
                    }
                    .disabled(!viewModel.isPinValid)
                    .frame(maxWidth: .infinity)
                    .accessibilityLabel("Save Transaction PIN")
                }
                
                if viewModel.isLoading {
                    ProgressView()
                }
            }
            .navigationTitle("Transaction PIN")
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("Cancel") {
                        viewModel.showPinSetup = false
                        viewModel.newPin = ""
                        viewModel.confirmPin = ""
                        viewModel.pinValidationMessage = nil
                    }
                }
            }
        }
    }
}

// MARK: - Preview

#Preview {
    SecurityView()
}
