replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-transaction-ledger
  pullPolicy: IfNotPresent
  tag: "0.0.2"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels:
  app: transaction-ledger
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9337
  targetPort: 9337
resources:
  requests:
    cpu: 200m
    memory: 144Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 512Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: transaction-ledger
  appPort: 9337
  enableMetrics: true
  enabled: true
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  ACCOUNT_SVC_URL: "http://core-accounts.54agent.svc.cluster.local:9300"
  APP_PORT: "9337"
  PORT_BASE: "9337"
  SERVICE_GROUP: transaction-ledger
  SERVICES: "transaction-ledger"
