apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    instance: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
