replicaCount: 1
image:
  repository: registry.digitalocean.com/talentgraph-auth/54agent-channels-messaging
  pullPolicy: IfNotPresent
  tag: "0.0.5"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: 54agent
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  ports:
    - port: 9256
    - port: 9257
    - port: 9258
    - port: 9259
    - port: 9260
    - port: 9261
    - port: 9262
    - port: 9263
    - port: 9264
    - port: 9265
    - port: 9266
    - port: 9267
    - port: 9268
    - port: 9269
    - port: 9270
    - port: 9271
    - port: 9272
resources:
  requests:
    cpu: 200m
    memory: 272Mi
  limits:
    ephemeral-storage: 512Mi
    cpu: 1000m
    memory: 1088Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
dapr:
  appId: channels-messaging
  appPort: 9256
  enableMetrics: true
  enabled: false
  metricsPort: 9099
  sidecarListenAddresses: "0.0.0.0"
  cpu-request: 100m
  cpu-limit: 300m
  memory-request: 250Mi
  memory-limit: 1000Mi
secrets:
  APP_PORT: "9256"
  PORT_BASE: "9256"
  SERVICE_GROUP: channels-messaging
  SERVICES: "communication-gateway,communication-hub,communication-service,communication-shared,messaging-service,multilingual-integration-service,notification-service,omnichannel-middleware,push-notification-service,realtime-notification-service,realtime-translation,sms-gateway,sms-service,sms-transaction-bridge,translation-service,unified-communication-hub,unified-communication-service"
